variable "project_name" {}
variable "region" {}
variable "instance_type" {}
variable "asg_min_size" {}
variable "asg_desired_capacity" {}
variable "asg_max_size" {}
variable "amis" {}
variable "public_subnet_az1_id" {}
variable "public_subnet_az2_id" {}
variable "alb_target_group_arn" {}
variable "inctance_security_group_id" {}