variable "project_name" {}
variable "aws_region" {}
variable "instance_type" {}
variable "asg_min_size" {}
variable "asg_desired_capacity" {}
variable "asg_max_size" {}
variable "amis" {}
variable "subnet_az_a_id" {}
variable "subnet_az_b_id" {}
variable "alb_target_group_arn" {}
variable "inctance_security_group_id" {}